/**
 * Markdown export — generates a structured .md file the trainer can open in
 * Obsidian, Notion, VS Code, Typora, etc.
 *
 * Structure:
 *   # Document title
 *   ## Unit info
 *   ### Section (Elements & PCs / Foundation Skills / PE / KE / AC)
 *   Markdown table per section
 */
import { saveAs } from 'file-saver';
import type { UnitOfCompetency } from '@workspace/api-client-react';
import { buildRows } from './unit-rows';
import type { Row } from './unit-rows';

type CellState = Record<string, string[]>;

// Escape pipe characters inside table cells
const esc = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

function mdTable(
  contentRows: Row[],
  numTasks: number,
  headers: string[],
  cells: CellState,
): string {
  const colHeaders = ['**Performance Criteria / Requirement**', ...headers.map(h => `**${esc(h)}**`)];
  const sep        = Array(numTasks + 1).fill('---');

  const lines: string[] = [
    `| ${colHeaders.join(' | ')} |`,
    `| ${sep.join(' | ')} |`,
  ];

  for (const row of contentRows) {
    if (row.kind === 'span') {
      let label: string;
      if (row.style === 'element')       label = `**${esc(row.label)}**`;
      else if (row.style === 'section')  label = `**— ${esc(row.label)} —**`;
      else                               label = `*${esc(row.label)}*`;

      const empties = Array(numTasks).fill('');
      lines.push(`| ${[label, ...empties].join(' | ')} |`);
    } else {
      const saved   = cells[row.key] ?? [];
      const dataCols = Array.from({ length: numTasks }, (_, i) => esc(saved[i] ?? ''));
      lines.push(`| ${[esc(row.label), ...dataCols].join(' | ')} |`);
    }
  }

  return lines.join('\n');
}

export function exportToMarkdown(
  unit: UnitOfCompetency,
  numTasks: number,
  headers: string[],
  cells: CellState,
  docTitle: string,
): void {
  const rows    = buildRows(unit);
  const heading = docTitle || `${unit.code} — ${unit.title}`;

  // Split rows into sections separated by 'section' span rows
  // so each section gets its own sub-heading + table
  type Section = { heading: string; rows: Row[] };
  const sections: Section[] = [];
  let current: Section = { heading: 'Elements & Performance Criteria', rows: [] };

  for (const row of rows) {
    if (row.kind === 'span' && row.style === 'section') {
      if (current.rows.length > 0) sections.push(current);
      current = { heading: row.label, rows: [] };
    } else {
      current.rows.push(row);
    }
  }
  if (current.rows.length > 0) sections.push(current);

  const parts: string[] = [
    `# ${heading}`,
    '',
    `**Unit:** ${unit.code}  `,
    `**Title:** ${unit.title}  `,
    `**Assessment tasks:** ${numTasks}  `,
    unit.status ? `**Status:** ${unit.status}  ` : '',
    unit.release ? `**Release:** ${unit.release}` : '',
    '',
    '---',
    '',
  ];

  if (unit.description) {
    parts.push(`> **Application:** ${unit.description.replace(/\n/g, ' ')}`);
    parts.push('');
  }

  for (const section of sections) {
    parts.push(`## ${section.heading}`);
    parts.push('');
    parts.push(mdTable(section.rows, numTasks, headers, cells));
    parts.push('');
  }

  parts.push('---');
  parts.push('');
  parts.push('*Generated by [Map App 3.0](https://github.com/stuanderson415-coder/map-app) — GNU GPL v3*');

  const md   = parts.filter(Boolean).join('\n');
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const name = (docTitle || unit.code).replace(/[^a-z0-9_\-]/gi, '_').slice(0, 50);
  saveAs(blob, `${unit.code}_mapping_${name}.md`);
}
